# Generated by Django 3.0.6 on 2020-05-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('ini-users', 'Usuarios'), ('ini-rocket', 'Foguete'), ('ini-stats-up', 'Grafico'), ('ini-mobile', 'Mobile'), ('ini-layers', 'Design'), ('ini-cog', 'Engrenagem')], max_length=12, verbose_name='Icone'),
        ),
    ]
